[package]
name = "oxide"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
env_logger = "0.11"
clap = { version = "4.5.38", features = ["derive"] }
ratatui = "0.29.0"
crossterm = "0.29.0"

[features]
log_mem_access = []
