[package]
name = "oxide"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
env_logger = "0.11"
clap = { version = "4.5.38", features = ["derive"] }
ratatui = "0.29.0"
crossterm = "0.29.0"
tui-textarea = "0.7.0"
num-traits = "0.2.19"
once_cell = "1.21.3"

[features]
log_mem_access = []
